spring:
  datasource:
    url: jdbc:h2:mem:shawermacloud
    username: admin
    password: admin
    generate-unique-name: false
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

